### ISSUE TITLE
location of Foxx apps

### ISSUE THREAD

**Issue by eyesee1** [arangodb/arangodb-docker#25]
Looks like arangodb is actually putting its Foxx apps at `/var/lib/arangodb3-apps`, not `/var/lib/arangodb-apps3` -- and the dir they are actually in is not shared to the host OS. (Makes working on Foxx apps pretty annoying -- have to manually zip and then upload through the web UI after each change.

Here's my Kitematic screen:

![screen shot 2016-07-09 at 12 36 13 pm](https://cloud.githubusercontent.com/assets/2981890/16709288/c298244a-45d1-11e6-9eb8-a911451008b7.png)
.)

In the dir listing of `/var/lib` you can see both dirs, but when I install a Foxx it goes to `/var/lib/arangodb3-apps`.

```
# ls -l /var/lib
total 41
drwxr-xr-x  7 root     root     4096 Jul  1 17:13 apt
drwxr-xr-x  2 root     root       68 Jul  8 22:30 arangodb-apps3
drwxr-xr-x  8 arangodb root      272 Jul  8 22:30 arangodb3
drwxr-xr-x  4 arangodb arangodb 4096 Jul  8 22:30 arangodb3-apps
drwxr-xr-x 13 root     root     4096 Jul  1 17:13 dpkg
drwxr-xr-x  2 root     root     4096 Apr  6  2015 initscripts
drwxr-xr-x  2 root     root     4096 Apr  6  2015 insert
drwxr-xr-x  2 root     root     4096 May 30 04:18 misc
drwxr-xr-x  2 root     root     4096 Jun  8 16:29 pam
drwxr-xr-x  3 root     root     4096 Jun  8 16:29 systems
drwxr-xr-x  2 root     root     4096 Nov 23  2012 update-rc.d
drwxr-xr-x  2 root     root     4096 Apr  6  2015 urandom
```

**Comment by m0ppers** [comment]
wow embarassing :flushed:

Thanks for reporting.

will be fixed with the next (3.0.3) release. The correct one is `/var/lib/arangodb3-apps`. I don't really know about kitematic but I guess you can override the volumes (probably the change button should reveal that functionality)?

On the command line you would simply add another volume like so:

`docker run -v ~/apps:/var/lib/arangodb3-apps -e ARANGO_NO_AUTH=1 aranngodb/arangodb:3.0.2`

Closing for now.
