### ISSUE TITLE
Building default Docker.local fails

### ISSUE THREAD

**Issue by igaln** [arangodb/arangodb-docker#32]
getting a 404 when running hooks on ca-certificates

Resolving www.arangodb.com (www.arangodb.com)... 85.214.140.94
Connecting to www.arangodb.com (www.arangodb.com)|85.214.140.94|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-04-03 16:45:02 ERROR 404: Not Found.

The command '/bin/sh -c apt-get update &&     apt-get install -y --no-install-recommends         libgoogle-perftools4         ca-certificates         pwgen         wget     &&     rm -rf /var/lib/apt/lists/* &&     wget ${ARANGO_SIGNATURE_URL} &&           wget ${ARANGO_PACKAGE_URL} &&             gpg --verify ${ARANGO_PACKAGE}.asc &&     dpkg -i ${ARANGO_PACKAGE} &&     sed -ri         -e 's!127\.0\.0\.1!0.0.0.0!g'         -e 's!^(file\s*=).*!\1 -!'         -e 's!^#\s*uid\s*=.*!uid = arangodb!'         -e 's!^#\s*gid\s*=.*!gid = arangodb!'         /etc/arangodb/arangod.conf     &&     apt-get purge -y --auto-remove ca-certificates wget &&     rm -f ${ARANGO_PACKAGE}*' returned a non-zero code: 8

**Comment by dothebart** [comment]
Whats the actual complete URL?

**Comment by ghost** [comment]
Package URL construction seems off, there is not just **@VERSION@** to change, but also **@REPO_TL_DIR@**? I am using `Dockerfile31.templ` here but since it is possible to set the version in the dockerfile, I do not understand why there are dockerfiles by version.

How would I have it output the requested URL?

The error for me:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found
The command '/bin/sh -c curl --fail -O ${ARANGO_SIGNATURE_URL} &&           curl --fail -O ${ARANGO_PACKAGE_URL} &&             gpg --verify ${ARANGO_PACKAGE}.asc &&     (echo arangodb3 arangodb3/password password test | debconf-set-selections) &&     (echo arangodb3 arangodb3/password_again password test | debconf-set-selections) &&     DEBIAN_FRONTEND="noninteractive" dpkg -i ${ARANGO_PACKAGE} &&     rm -rf /var/lib/arangodb3/* &&     sed -ri         -e 's!127\.0\.0\.1!0.0.0.0!g'         -e 's!^(file\s*=).*!\1 -!'         -e 's!^#\s*uid\s*=.*!uid = arangodb!'         -e 's!^#\s*gid\s*=.*!gid = arangodb!'         /etc/arangodb3/arangod.conf     &&     DEBIAN_FRONTEND="noninteractive" apt-get purge -y --auto-remove ca-certificates &&     rm -f ${ARANGO_PACKAGE}*' returned a non-zero code: 22

```

**Comment by ghost** [comment]
the @VERSION@ should be in the format 3.1.20

versions to pick from
https://www.arangodb.com/repositories/arangodb31/Debian_8.0/amd64/

**Comment by dothebart** [comment]
@Thijxx  Its `.templ` since its intended to be processed by `addversion.sh` and to be put into `jessie/3.1.20/Dockerfile`. 

Its the layout the docker library recommends.

**Comment by dothebart** [comment]
@igaln since the .local file is intended to use a copy of a local docker file that comes right out of the build process it doesn't verify any signatures. Therefore I've removed the signature check, this should work now.

You should use the `DockerfileN.local` matching your release branch - N="" -> 2.8; N = 3 -> 3.0; N = 31 => 3.1; N = 32 -> 3.2 (currently devel/alpha)

**Comment by ghost** [comment]
great, thanks
